/**
 * Answer exercises right or wrong, using the item the app exposes through the opt-in e2e hook
 * (window.__MC_E2E__.items[exerciseId], set by <ExerciseShell>).
 *
 * To support a newly implemented exercise type, add an entry to ANSWERERS: given the item (as generated by
 * packages/core) produce the UI interaction for a correct and for a wrong answer. Types without an answerer
 * are still covered by the generic render/reveal/next/finish checks in exercises.spec.ts.
 */
import { expect, type Locator, type Page } from '@playwright/test';
import { clickKey, midi } from './app';
import { pcOf } from './content';

export interface ShellItem<T = Record<string, any>> {
  index: number;
  total: number;
  item: T & { type: string; solution: string; choices?: { value: string; label: string }[] };
}

export function exerciseLocator(page: Page, id: string): Locator {
  return page.locator(`[data-testid="exercise-${id}"]`);
}

export async function currentItem(page: Page, id: string): Promise<ShellItem> {
  await expect.poll(() => page.evaluate((i) => !!(window as any).__MC_E2E__?.items?.[i], id), { message: `item hook for ${id}` }).toBe(true);
  return page.evaluate((i) => JSON.parse(JSON.stringify((window as any).__MC_E2E__.items[i])), id);
}

/** Wait until the shell shows item `index` (after Next). */
export async function waitForIndex(page: Page, id: string, index: number): Promise<ShellItem> {
  await expect.poll(async () => (await currentItem(page, id)).index, { message: `exercise ${id} at item ${index}` }).toBe(index);
  return currentItem(page, id);
}

async function clickChoiceAt(section: Locator, i: number) {
  await section.locator('.choice-grid button').nth(i).click();
}

async function pressNotes(page: Page, section: Locator, notes: number[]) {
  for (const n of notes) {
    const onScreen = await section.locator(`[data-midi="${n}"]`).count();
    if (onScreen) await clickKey(page, section, n);
    else {
      await midi.noteOn(page, n, 100);
      await midi.noteOff(page, n);
    }
  }
}

type Answerer = (page: Page, section: Locator, it: ShellItem['item'], correct: boolean) => Promise<void>;

const choiceByValue: Answerer = async (_page, section, it, correct) => {
  const choices = it.choices ?? [];
  const idx = correct ? choices.findIndex((c) => c.value === it.answer) : choices.findIndex((c) => c.value !== it.answer);
  expect(idx, `choice for ${correct ? 'correct' : 'wrong'} answer ${it.answer} in ${JSON.stringify(choices)}`).toBeGreaterThanOrEqual(0);
  await clickChoiceAt(section, idx);
};

export const ANSWERERS: Record<string, Answerer> = {
  'ear-note': choiceByValue,
  'ear-octave': choiceByValue,
  'ear-interval': choiceByValue,
  'ear-chord': choiceByValue,
  quiz: async (_page, section, it, correct) => {
    const right: number[] = it.correct;
    const n = (it.choices ?? []).length;
    const wrongIdx = [...Array(n).keys()].find((i) => !right.includes(i));
    if (it.multi) {
      for (const i of correct ? right : [wrongIdx!]) await clickChoiceAt(section, i);
      await section.getByRole('button', { name: 'Check' }).click();
    } else {
      await clickChoiceAt(section, correct ? right[0]! : wrongIdx!);
    }
  },
  'quiz-input': async (_page, section, it, correct) => {
    const accepted: string[] = it.accepted;
    let value = accepted[0]!;
    if (!correct) {
      if (it.kind === 'number') value = '987654321';
      else if (it.kind === 'note') {
        const pcs = new Set(accepted.map(pcOf));
        value = ['C', 'D', 'E', 'F#', 'Ab'].find((n) => !pcs.has(pcOf(n)))!;
      } else value = 'definitely-wrong-answer';
    }
    await section.getByLabel('Answer').fill(value);
    await section.getByRole('button', { name: 'Check' }).click();
  },
  'read-note': async (page, section, it, correct) => {
    if (it.answerKind === 'name') {
      const choices = it.choices ?? [];
      const idx = choices.findIndex((c) => (pcOf(c.value) === it.midi % 12) === correct);
      await clickChoiceAt(section, idx);
    } else {
      await pressNotes(page, section, [correct ? it.midi : it.midi + 2]);
    }
  },
  'play-notes': async (page, section, it, correct) => {
    const targets: number[] = it.midis;
    await pressNotes(page, section, correct ? targets : targets.map((m) => m + 1));
  },
};

export function canAnswer(type: string): boolean {
  return type in ANSWERERS;
}

/** Answer the current item of exercise `id`; waits for the feedback. */
export async function answer(page: Page, id: string, correct: boolean): Promise<ShellItem> {
  const section = exerciseLocator(page, id);
  const cur = await currentItem(page, id);
  const fn = ANSWERERS[cur.item.type];
  if (!fn) throw new Error(`no answerer for ${cur.item.type}`);
  await fn(page, section, cur.item, correct);
  await expect(section.locator('.feedback')).toHaveClass(correct ? /\bok\b/ : /\bbad\b/);
  return cur;
}

export async function next(page: Page, id: string): Promise<void> {
  await exerciseLocator(page, id).locator('.exercise-foot button.primary').click();
}

/**
 * The summary card shown after Finish, or null if it does not appear within `timeout`.
 * (BUG-03: on lesson pages the shell is remounted right after Finish, so the summary never shows.)
 */
export async function summaryText(page: Page, id: string, timeout = 2500): Promise<string | null> {
  const summary = exerciseLocator(page, id).getByTestId('exercise-summary');
  try {
    await summary.waitFor({ state: 'visible', timeout });
    return (await summary.textContent()) ?? '';
  } catch {
    return null;
  }
}

/** Answer every item (all correct, or the given pattern) and press Finish. Returns the summary text (or null). */
export async function completeSet(page: Page, id: string, pattern: (i: number) => boolean = () => true): Promise<string | null> {
  const { total } = await currentItem(page, id);
  for (let i = 0; i < total; i++) {
    await waitForIndex(page, id, i);
    await answer(page, id, pattern(i));
    await next(page, id);
  }
  return summaryText(page, id);
}

/** Reveal every item and finish (works for every implemented type, no answerer needed). */
export async function revealAll(page: Page, id: string): Promise<string | null> {
  const { total } = await currentItem(page, id);
  const section = exerciseLocator(page, id);
  for (let i = 0; i < total; i++) {
    await waitForIndex(page, id, i);
    await section.getByRole('button', { name: 'Reveal' }).click();
    await expect(section.locator('.feedback')).toContainText('Answer:');
    await next(page, id);
  }
  return summaryText(page, id);
}
